version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "${POSTGRES_PORT_PC}:${POSTGRES_PORT_CONTAINER}" # Usa variables para los puertos
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    ports:
      - "${PGADMIN_LISTEN_PORT_PC}:${PGADMIN_LISTEN_PORT_CONTAINER}" # Usa variables para los puertos
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

volumes:
  postgres_data: # Volumen para persistencia de PostgreSQL
